export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const GET_WEATHER_DATA_SUCCESS = 'GET_WEATHER_DATA_SUCCESS';
export const GET_WEATHER_DATA_FAIL = 'GET_WEATHER_DATA_FAIL';
export const GET_FAKE_WEATHER_DATA = 'GET_FAKE_WEATHER_DATA';
